site_name: RADocs
site_url: 'https://docs.retroachievements.org/'
site_description: >-
  RetroAchievements' documentation page.
repo_name: 'televandalist/RADocsTEMP'
repo_url: 'https://github.com/televandalist/RADocsTEMP'
nav:
  - 'RADocs': 
    - Home: 'index.md'
    - About Us: 'about-us.md'
    - Downloads: 'downloads.md'
    - Glossary: 'glossary.md'
  - 'Guidelines':
    - Overview: 'guidelines/overview.md'
    - 'General':
      - RetroAchievements Manifesto: 'guidelines/ra-manifesto.md'
      - Users Code of Conduct: 'guidelines/user-coc.md'
      - Global Leaderboard and Achievement Hunting Rules: 'guidelines/global-leaderboard-and-achievement-hunting-rules.md'
      - Ticket Etiquette: 'guidelines/ticket-etiquette.md'
    - 'Development':
      - Developer Code of Conduct: 'guidelines/dev-coc.md'
      - DevCoC FAQ: 'guidelines/dev-coc-faq.md'
      - Content Guidelines: 'guidelines/contentguidelines.md'
      - Achievement Scoring: 'guidelines/achievement-scoring.md'
  - 'Games':
    - Games Home: 'games/games-home.md'
    - Requests: 'games/requests.md'
    - 'Supported Systems':
      - Console ID List: 'games/console-ids.md'
      - Libretro Core Support: 'games/libretro-core-support.md'
      - Game Identification: 'games/game-identification.md'
      - Supported Consoles: 'games/supported-consoles.md'
    - 'Emulators':
      - RALibretro: 'games/emulators/ralibretro.md'
      - RAMeka: 'games/emulators/rameka.md'
      - RANes: 'games/emulators/ranes.md'
      - RAP64: 'games/emulators/rap64.md'
      - RAQUASI88: 'games/emulators/raquasi88.md'
      - RASnes9x: 'games/emulators/rasnes9x.md'
      - RAVBA: 'games/emulators/ravba.md'
  - 'General':
    - Players Home: 'general/home.md'
    - RetroArch: 'general/retroarch.md'
    - RALibretro: 'general/ralibretro.md'
    - User FAQ: 'general/userfaq.md'
    - 'Community':
      - Community Home: 'general/community/home.md'
      - RANews: 'general/community/ranews.md'
      - 'Events':
        - Events Home: 'general/community/events.md'
        - Devquest: 'general/community/events/devquest.md'
        - Rollouts: 'general/community/events/rollouts.md'
      - 'Discord':
        - Discord Home: 'general/community/discord.md'
        - RABot: 'general/community/discord/rabot%2C-the-ra-discord-robot.md'
  - 'Developers':
    - Developers Home: 'developers/devs-home.md'
    - 'Getting Started':
      - How to Become an Achievement Developer: 'developers/how-to-become-an-achievement-developer.md'
      - Getting Started as an Achievement Developer: 'developers/getting-started-as-an-achievement-developer.md'
      - Junior Developers: 'developers/junior-devs.md'
      - Code Review Checklist: 'developers/code-review-checklist.md'
      - New Achievement Set Checklist: 'developers/new-achievement-set-checklist.md'
    - Memory Inspector Overview: 'developers/memory-inspector-overview.md'
    - 'Achievement Logic Features':
      - Logic Features Home: 'developers/features/logic-features-home.md'
      - Hit Counts: 'developers/features/hit-counts.md'
      - Delta Values: 'developers/features/delta-values.md'
      - Prior Values: 'developers/features/prior-values.md'
      - 'Flags':
        - ResetIf Flag: 'developers/features/flags/resetif.md'
        - ResetNextIf Flag: 'developers/features/flags/resetnextif.md'
        - PauseIf Flag: 'developers/features/flags/pauseif.md'
        - AndNext and OrNext Flags: 'developers/features/flags/andnext-ornext.md'
        - AddSource Flag: 'developers/features/flags/addsource.md'
        - SubSource Flag: 'developers/features/flags/subsource.md'
        - AddHits and SubHits Flags: 'developers/features/flags/addhits-subhits.md'
        - AddAddress Flag: 'developers/features/flags/addaddress.md'
        - Measured Flag: 'developers/features/flags/measured.md'
        - Trigger Flag: 'developers/features/flags/trigger.md'
      - BitCount Size: 'developers/features/bitcount-size.md'
      - Alt Groups: 'developers/features/alt-groups.md'
      - Value Definition: 'developers/features/value-definition.md'
      - Condition Syntax: 'developers/features/condition-syntax.md'
      - Minimum Required Versions for Logic Features: 'developers/features/minimum-required-versions-for-logic-features.md'
    - Console Specific Tips: 'developers/console-specific-tips.md'
    - 'Achievement Creation Tutorials':
      - Achievement Creation Tutorials Home: 'developers/achievement-creation-tutorials.md'
    - Logic Examples: 'developers/logic-examples.md'
    - 'Real Examples':
      - Real Examples Home: 'developers/real-examples.md'
      - Using Hit Counts as a Timer: 'developers/realexamples/using-hit-counts-as-a-timer.md'
      - Using Delta Values and Hit Counts to Detect an Increment: 'developers/realexamples/using-delta-values-and-hit-counts-to-detect-an-increment.md'
      - Circumvent the Problem of a Counter Incrementing Twice in the Same Frame: 'developers/realexamples/circumvent-the-problem-of-a-counter-incrementing-twice-in-the-same-frame.md'
      - Creating a Timer with ResetIf Hits based on the Speed of the Game: 'developers/realexamples/creating-a-timer-with-resetIf-hits-based-on-the-speed-of-the-game.md'
      - Using Add Source and Deltas for Collectibles or Similar Achievements: 'developers/realexamples/addsource-collectibles.md'
    - Achievement Templates: 'developers/achievement-templates.md'
    - Tips and Tricks: 'developers/tips-and-tricks.md'
    - Difficulty Scale and Balance: 'developers/difficulty-scale-and-balance.md'
    - Achievement Design: 'developers/design.md'
    - Set Development Roadmap: 'developers/set-development-roadmap.md'
    - Achievement Set Revisions: 'developers/achievement-set-revisions.md'
    - Leaderboards: 'developers/leaderboards.md'
    - Rich Presence: 'developers/rich-presence.md'
    - Working with the Right ROM: 'developers/working-with-the-right-rom.md'
    - Achievements for ROM Hacks: 'developers/achievements-for-rom-hacks.md'
    - Subsets: 'developers/subsets.md'
    - 'Resources':
      - 'developers/resources/links.md'
  - 'Artists':
    - Artists Home: 'artists/art-home.md'
    - Badge and Icon Creation: 'artists/badge-and-icon-creation.md'
  - 'Support':
    - FAQ: 'support/faq.md'
    - Multi Disc Games Tutorial: 'support/multi-disc-games-tutorial.md'
    - Working with DLC for the PlayStation Portable: 'support/working-with-dlc-for-the-playstation-portable.md'
    - How to configure OBS Studio to see the popups: 'support/how-to-configure-obs-studio-to-see-the-popups.md'
    - My Game Is Not Loading Achievements: 'support/my-game-is-not-loading-achievements.md'
    - System X Wen: 'support/system-x-wen.md'
    - How to Contribute if You Are Not a Developer: 'support/how-to-contribute-if-you-are-not-a-developer.md'
    - Why You Should Not Use the Load State Feature: 'support/why-you-should-not-use-the-load-state-feature.md'
    - A Message for Achievement Hunters and Completionists About Revisions: 'support/a-message-for-achievement-hunters-and-completionists-about-revisions.md'
    - Editing Docs: 'support/editingdocs.md'
  - 'Other':
    - Other Home: 'sort/other-home.md'
    - Badge Event Creation Policy: 'sort/badge-event-creation-policy.md'
    - Combining Flags: 'sort/combining-flags.md'
    - Contributing with the Docs: 'sort/contributing-with-the-docs.md'
    - Forum Labels: 'sort/forum-labels.md'
    - RALib on Linux: 'sort/how-to-run-ralibretro-on-linux.md'
    - LB Bug and Improvement: 'sort/leaderboard-bug-list-and-improvement-ideas.md'
    - New Test Overview: 'sort/newtest-overview.md'
    - RA In Review: 'sort/ra-in-review.md'
    - RA-Trackers: 'sort/ra-trackers.md'
    - Regional Compatibility: 'sort/regional-compatibility.md'
    - Reporting Broken Achievements: 'sort/reporting-a-broken-achievement.md'
    - System Memory Mapping: 'sort/systems-memory-mapping.md'
    - Testing for Demo Mode: 'sort/testing-for-demo-mode.md'
    - The Cheevo Workshop: 'sort/cheevo-workshop.md'
    - Useful Links: 'sort/useful-links.md'
    - Conditional Resets: 'sort/using-a-conditional-reset.md'

extra:
  version: '0.0.1'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  social:
    - icon: fontawesome/solid/globe
      link: https://retroachievements.org
      name: RetroAchievements Website
    - icon: fontawesome/brands/github
      link: https://github.com/RetroAchievements/
      name: RetroAchievements GitHub Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dq2E4hE
      name: RetroAchievements Discord Server
    - icon: fontawesome/brands/twitter
      link: https:twitter.com/RetroCheevos
      name: RetroAchievements on Twitter

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      guess_lang: false
  - markdown.extensions.nl2br
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: accept
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: libretro
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - pymdownx.tasklist:
      clickable_checkbox: true

theme:
  name: material
  custom_dir: 'docs/theme'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.tabs.sticky
    - content.tabs.link
  palette:
    primary: 'blue'
    accent: 'light blue'
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  favicon: 'icons/favicon.ico'

extra_css:
  - stylesheets/codehilite.css
  - stylesheets/tablesort.css
  - stylesheets/dark_theme.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
