site_name: RADocs
site_url: 'https://docs.retroachievements.org/'
site_description: >-
  RetroAchievements' documentation page.
repo_name: 'televandalist/RADocsTEMP'
repo_url: 'https://github.com/televandalist/RADocsTEMP'
nav:
  - 'Home': 
    - Home: 'index.md'
    - About Us: 'about-us.md'
    - Contributing with the Docs: 'contributing-with-the-docs.md'
  - 'Guidelines':
    - Overview: 'guidelines/overview.md'
    - 'General':
      - RetroAchievements Manifesto: 'guidelines/ra-manifesto.md'
      - Users Code of Conduct: 'guidelines/user-coc.md'
      - Global Leaderboard and Achievement Hunting Rules: 'guidelines/global-leaderboard-and-achievement-hunting-rules.md'
      - Ticket Etiquette: 'guidelines/ticket-etiquette.md'
      - Manual Unlocks: 'guidelines/manualunlocks.md'
      - Badge Event Creation Policy: 'guidelines/badge-event-creation-policy.md'
    - 'Developers':
      - Developer Code of Conduct: 'guidelines/dev-coc.md'
      - DevCoC FAQ: 'guidelines/dev-coc-faq.md'
    - 'Achievements':
      - New Achievement Set Checklist: 'guidelines/new-achievement-set-checklist.md'
      - Content Guidelines: 'guidelines/contentguidelines.md'
      - Achievement Set Requirements: 'guidelines/achievement-set-requirements.md'
      - Achievements for ROM Hacks: 'guidelines/achievements-for-rom-hacks.md'
      - Achievement Scoring: 'guidelines/achievement-scoring.md'
      - Revision Guidelines: 'guidelines/achievement-set-revisions.md'
  - 'Development':
    - Developers Home: 'development/devs-home.md'
    - 'Getting Started':
      - How to Become an Achievement Developer: 'development/how-to-become-an-achievement-developer.md'
      - Getting Started as an Achievement Developer: 'development/getting-started-as-an-achievement-developer.md'
      - Junior Developers: 'development/junior-devs.md'
    - 'Achievement Design':
      - Achievement Design: 'development/design.md'
      - Difficulty Scale and Balance: 'development/difficulty-scale-and-balance.md'
      - Set Development Roadmap: 'development/set-development-roadmap.md'
    - 'Achievement Creation':
      - Memory Inspector Overview: 'development/memory-inspector-overview.md'
      - 'Achievement Logic Features':
        - Logic Features Home: 'development/logic-features-home.md'
        - Hit Counts: 'development/hit-counts.md'
        - Delta Values: 'development/delta-values.md'
        - Prior Values: 'development/prior-values.md'
        - 'Flags':
          - ResetIf Flag: 'development/resetif.md'
          - ResetNextIf Flag: 'development/resetnextif.md'
          - PauseIf Flag: 'development/pauseif.md'
          - AndNext and OrNext Flags: 'development/andnext-ornext.md'
          - AddSource Flag: 'development/addsource.md'
          - SubSource Flag: 'development/subsource.md'
          - AddHits and SubHits Flags: 'development/addhits-subhits.md'
          - AddAddress Flag: 'development/addaddress.md'
          - Measured Flag: 'development/measured.md'
          - Trigger Flag: 'development/trigger.md'
        - BitCount Size: 'development/bitcount-size.md'
        - Alt Groups: 'development/alt-groups.md'
        - Value Definition: 'development/value-definition.md'
        - Condition Syntax: 'development/condition-syntax.md'
        - Minimum Required Versions for Logic Features: 'development/minimum-required-versions-for-logic-features.md'
      - Achievement Creation Tutorials: 'development/achievement-creation-tutorials.md'
      - Conditional Resets: 'development/conditional-resets.md'
      - Testing for Demo Mode: 'development/testing-for-demo-mode.md'
      - LB Bug and Improvement: 'development/leaderboard-bug-list-and-improvement-ideas.md'
      - Combining Flags: 'development/combining-flags.md'
      - Things to Avoid and Why: 'development/avoid.md'
      - Achievement Templates: 'development/achievement-templates.md'
      - Tips and Tricks: 'development/tips-and-tricks.md'
      - Console Specific Tips: 'development/console-specific-tips.md'
    - Subsets: 'development/subsets.md'
    - 'Badges and Icon Creation':
      - Overview: 'development/badgesoverview.md'
      - Art Helpers and Requests: 'development/badgerequests.md'
      - Tutorials: 'development/badgetutorials.md'
      - Icon Gauntlet: 'development/icongauntlet.md'
    - Leaderboards: 'development/leaderboards.md'
    - Rich Presence: 'development/rich-presence.md'
    - RATools: 'development/ratools.md'
    - Dev Tips: 'development/devtips.md'
    - Case Studies: 'development/casestudies.md'
    - Dev Logs: 'development/devlogs.md'
    - System Memory Mapping: 'development/systems-memory-mapping.md'
    - Troubleshooting: 'development/troubleshooting.md'
  - 'Games':
    - Games Home: 'games/games-home.md'
    - Requests: 'games/requests.md'
    - 'Entry, Hash, and Patch Management':
      - Working with the Right ROM: 'games/working-with-the-right-rom.md'
      - Creating Entries: 'games/creating-entries.md'
      - Hash Labels: 'games/hashlabels.md'
      - Compatibility Testing: 'games/compatibility-testing.md'
      - RAPatches: 'games/rapatches.md'
      - Naming Conventions: 'games/namingconventions.md'
    - 'Supported Systems':
      - Console ID List: 'games/console-ids.md'
      - Libretro Core Support: 'games/libretro-core-support.md'
      - Game Identification: 'games/game-identification.md'
      - Console Support: 'games/console-support.md'
      - Testing Cores and Emulators: 'games/testing.md'
    - 'Emulators':
      - RetroArch: 'games/retroarch.md'
      - RALibretro: 'games/ralibretro.md'
      - RAQUASI88: 'games/raquasi88.md'
  - 'Community':
    - Community Home: 'community/home.md'
    - RANews: 'community/ranews.md'
    - 'Events':
      - Events Home: 'community/events.md'
      - Achievement of the Week: 'community/aotw.md'
      - Challenge League: 'community/challengeleague.md'
      - Daily Distractions: 'community/dailydistractions.md'
      - Devquest: 'community/devquest.md'
      - Leaderboard of the Month: 'community/lbotm.md'
      - Peak Streak: 'community/peakstreak.md'
      - QualityQuest: 'community/qualityquest.md'
      - RetroAchievements Roulette: 'community/rawr.md'
      - Rollouts: 'community/rollouts.md'
      - The Unwanted: 'community/theunwanted.md'
    - RAGuides: 'community/raguides.md'
    - Playtesters: 'community/playtesters.md'
    - 'Discord':
      - Discord Home: 'community/discord.md'
      - RABot: 'community/rabot%2C-the-ra-discord-robot.md'
    - RA In Review: 'community/ra-in-review.md'
    - RA-Trackers: 'community/ra-trackers.md'    
  - 'Resources and Support':
    - FAQ: 'support/faq.md'
    - Glossary: 'support/glossary.md'
    - Multi Disc Games Tutorial: 'support/multi-disc-games-tutorial.md'
    - Working with DLC for the PlayStation Portable: 'support/working-with-dlc-for-the-playstation-portable.md'
    - How to configure OBS Studio to see the popups: 'support/how-to-configure-obs-studio-to-see-the-popups.md'
    - My Game Is Not Loading Achievements: 'support/my-game-is-not-loading-achievements.md'
    - System X Wen: 'support/system-x-wen.md'
    - How to Contribute if You Are Not a Developer: 'support/how-to-contribute-if-you-are-not-a-developer.md'
    - Why You Should Not Use the Load State Feature: 'support/why-you-should-not-use-the-load-state-feature.md'
    - A Message for Achievement Hunters and Completionists About Revisions: 'support/a-message-for-achievement-hunters-and-completionists-about-revisions.md'
    - Reporting Broken Achievements: 'support/reporting-a-broken-achievement.md'
    - Useful Links: 'support/useful-links.md'

extra:
  version: '0.0.1'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  social:
    - icon: fontawesome/solid/globe
      link: https://retroachievements.org
      name: RetroAchievements Website
    - icon: fontawesome/brands/github
      link: https://github.com/RetroAchievements/
      name: RetroAchievements GitHub Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dq2E4hE
      name: RetroAchievements Discord Server
    - icon: fontawesome/brands/twitter
      link: https:twitter.com/RetroCheevos
      name: RetroAchievements on Twitter

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      guess_lang: false
  - markdown.extensions.nl2br
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: accept
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: libretro
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - pymdownx.tasklist:
      clickable_checkbox: true

theme:
  name: material
  custom_dir: 'docs/theme'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.tabs.sticky
    - content.tabs.link
  palette:
    primary: 'blue'
    accent: 'light blue'
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  favicon: 'icons/favicon.ico'

extra_css:
  - stylesheets/codehilite.css
  - stylesheets/tablesort.css
  - stylesheets/dark_theme.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
